version: '3.8'
services:
  animeseason:
    build: .
    container_name: animeseason
    ports:
      - "12345:12345"
    volumes:
      - /volume4/root4/AppData/AnimeSeason/database:/app/AnimeSeasonDb
      - /volume4/root4/AppData/AnimeSeason/config.ini:/app/config.ini
    restart: unless-stopped
